Repository brandonhach/rep, pull requests merged in 2024-07, with the labels that each got.

#25 PR: Comment Pagination
  package.json
  src/actions/comments/add-comment.ts
  src/actions/comments/get-comments.ts
  src/app/(protected)/profile/[id]/page.tsx
  src/components/profile/ui/Feeds/Comments.tsx
Labels: Medium, Pull Request

#26 PR: Pagination on Moodboard Tab
  src/actions/moodboards/add-moodboards.ts
  src/actions/moodboards/get-moodboards.ts
  src/app/(protected)/profile/[id]/page.tsx
  src/components/profile/ui/Showcase/Moodboard.tsx
Labels: Medium, Pull Request

#31 PR: Edit Description and Background Image of Profile Card
  package.json
  prisma/schema.prisma
  src/actions/profile-card/check-profilecard.ts
  src/actions/profile-card/edit-profilecard.ts
  src/app/(protected)/profile/[id]/page.tsx
  src/components/profile/ProfileCard.tsx
  src/components/profile/ui/ProfileEditButton.tsx
  src/types/types.ts
Labels: Small, Pull Request

#33 PR: Refine Home Page
  src/app/page.tsx
  src/components/home/CTA.tsx
  src/components/home/Hero.tsx
  src/components/home/ui/CTA/Globe.tsx
  src/components/home/ui/Hero/AuroraBG.tsx
  src/components/home/ui/Hero/Vortex.tsx
  src/components/ui/DirectionAwareHover.tsx.tsx
  src/components/ui/FancySearchBar.tsx
  src/components/ui/Globe.tsx
  src/components/ui/Navbar.tsx
  src/config/site-config.ts
  src/config/ui/globe/globe.json
  src/config/ui/globe/globeDependency.ts
Labels: Pull Request

#35 PR: Reputation Tab
  docker-compose.yml
  prisma/schema.prisma
  src/actions/comments/get-comments.ts
  src/actions/moodboards/get-moodboards.ts
  src/actions/rep/add-rep.ts
  src/app/(protected)/profile/[id]/page.tsx
  src/components/home/Hero.tsx
  src/components/profile/Feeds.tsx
  src/components/profile/ProfileCard.tsx
  src/components/profile/ui/Feeds/Comments.tsx
  src/components/profile/ui/Feeds/Rep.tsx
  src/components/profile/ui/Forms/ProfileForm.tsx
  src/components/profile/ui/Forms/RepForm.tsx
  src/components/profile/ui/RepButton.tsx
  src/components/profile/ui/Showcase/Moodboard.tsx
  src/components/ui/DirectionAwareHover.tsx
  src/components/ui/Navbar.tsx
  src/config/ui/globe/globeDependency.ts
  src/lib/profile-data.ts
  src/types/types.ts
Labels: Pull Request
